### ISSUE TITLE
Reaction to your own messages

### ISSUE THREAD

**Issue by Prinz-Eugen-Deep** [Konard/vk-bot#5]
The bot reacts to its own messages. It may be inconvenient to communicate
![изображение_2023-12-09_123137426](https://github.com/Konard/vk-bot/assets/105128133/ce70052d-5d07-467c-ba9c-3bba38490d82)

**Comment by Konard** [comment]
Closed by https://github.com/Konard/vk-bot/commit/61e033db03c4063486153cd49d380a0e9f7ff036
